# server
server:
  port: 8080
  servlet:
    context-path: /
    # encoding:
    #   charset: UTF-8
    #   enabled: true
    #   force: true

jwt:
  # HS512 알고리즘을 사용할 것이기 때문에 512bit, 즉 64byte 이상의 secret key를 사용해야 한다.
  # echo 'sdafasfasfdfdfsdsdfsdsf'|base64
  secret: ThisIsA_SecretKeyForJwtExampleThisIsA_SecretKeyForJwtExampleThisIsA_SecretKeyForJwtExampleThisIsA_SecretKeyForJwtExample

spring:
  datasource:
    # driver-class-name: org.h2.Driver
    # url: jdbc:h2:mem:test
    # username: sa
    # password:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test-board-server?serverTimezone=Asia/Seoul
    username: test-board-user
    password: test1234@
  jpa:
    hibernate:
      ddl-auto: create #create update none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
  sql:
    init:
      mode: always # 서버 시작시 항상 classpath의 sql문을 실행하도록 설정
      continue-on-error: true # 서버 시작시 sql문을 실행할 때 오류 무시하고 계속 진행
      data-locations: classpath:sql/data.sql # 서버 시작시 dml sql문을 실행할 위치 및 파일 지정
      # schema-locations: classpath:sql/schema.sql # 서버 시작시 ddl sql문을 실행할 위치 및 파일 지정
    
# log level
logging:
  logback:
    rollingpolicy:
      file-name-pattern: "/Users/djkang/dev/gundam/product-src/logs/gundam.%d{yyyy-MM-dd}.%i"
  pattern:
    file: "[%d{HH:mm:ss.SSS}][%-5level][%logger.%method:line%line] - %msg%n"
  file:
    name: /Users/djkang/dev/gundam/product-src/logs/gundam.log
    max-history: 300
  level:
    '[com.main.gundam.sample]': INFO
    org:
      springframework: INFO

