# server
server:
  port: 8080
  servlet:
    context-path: /
    # encoding:
    #   charset: UTF-8
    #   enabled: true
    #   force: true

jwt:
  secret: ThisIsA_SecretKeyForJwtExampleThisIsA_SecretKeyForJwtExampleThisIsA_SecretKeyForJwtExampleThisIsA_SecretKeyForJwtExample

spring:
  datasource:
    # driver-class-name: org.h2.Driver
    # url: jdbc:h2:mem:test
    # username: sa
    # password:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test-board-server?serverTimezone=Asia/Seoul
    username: test-board-user
    password: test1234@

  jpa:
    hibernate:
      ddl-auto: none #create update none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    
# log level
logging:
  logback:
    rollingpolicy:
      file-name-pattern: "/Users/djkang/dev/gundam/product-src/logs/gundam.%d{yyyy-MM-dd}.%i"
  pattern:
    file: "[%d{HH:mm:ss.SSS}][%-5level][%logger.%method:line%line] - %msg%n"
  file:
    name: /Users/djkang/dev/gundam/product-src/logs/gundam.log
    max-history: 300
  level:
    '[com.main.gundam.sample]': INFO
    org:
      springframework: INFO

